# Use the official Ryu SDN controller image (Pre-configured with Ryu)
FROM osrg/ryu:latest

# Install the Redis library for Python
# We use version 3.5.3 because it is stable with the Python 2 environment in this image
RUN pip install redis==3.5.3
